name: DATA606_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.5
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blinker=1.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.11.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cramjam=2.8.3
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - dash=2.18.2
  - debugpy=1.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fastparquet=2024.5.0
  - flask=3.0.3
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - intel-openmp=2024.2.0
  - ipykernel=6.29.5
  - ipython=8.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.5
  - kneed=0.8.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - levenshtein=0.25.1
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgoogle-cloud=2.32.0
  - libgoogle-cloud-storage=2.32.0
  - libgrpc=1.67.1
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libparquet=18.1.0
  - libpng=1.6.43
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.6.0
  - libutf8proc=2.9.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxgboost=2.1.3
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - lxml=5.2.2
  - lz4-c=1.10.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2024.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nb_conda_kernels=2.5.1
  - nbclassic=1.1.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - nltk=3.8.1
  - notebook=6.5.4
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.1
  - pandoc=3.2.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - plotly=5.22.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - py-xgboost=2.1.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-levenshtein=0.25.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - rapidfuzz=3.9.4
  - re2=2024.07.02
  - referencing=0.35.1
  - regex=2024.5.15
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.19.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=69.5.1
  - shap=0.46.0
  - six=1.16.0
  - slicer=0.0.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - tbb=2021.12.0
  - tenacity=8.5.0
  - terminado=0.18.1
  - thefuzz=0.22.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.7.1
  - treeinterpreter=0.2.2
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.42.34433
  - voila=0.5.7
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=10.4
  - werkzeug=3.0.3
  - wheel=0.43.0
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xgboost=2.1.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cryptography==42.0.8
      - faker==33.1.0
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.0
      - h5py==3.11.0
      - imageio==2.36.1
      - ipydeps==2024.33.0
      - ipyfilechooser==0.6.0
      - ipylogging==2020.342.1
      - keras==3.5.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lime==0.2.0.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.2.1
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.2
      - pem==23.1.0
      - pillow==11.0.0
      - protobuf==4.25.4
      - pycountry==24.6.1
      - pypki3==2024.139.1394
      - rich==13.7.1
      - scikit-image==0.25.0
      - sympy==1.13.1
      - temppath==2021.236.907
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - termcolor==2.4.0
      - tifffile==2024.12.12
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - wrapt==1.16.0
